version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      chengyu-net:

  web:
    build: .
    volumes:
      - ./src:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    stdin_open: true
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    networks:
      chengyu-net:

  selenium_chrome:
    image: seleniarm/standalone-chromium:116.0-20230828
    networks:
      chengyu-net:

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      chengyu-net:

networks:
  chengyu-net:
